[package]
name = "rust-yew"
version = "0.1.0"
authors = ["FundGao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.14.3", features = ["std_web"] }

[features]
std_web = ["stdweb"]
