[package]
name = "counter_std_web"
version = "0.1.1"
authors = ["Fund Gao <fundgao@gmail.com>"]
edition = "2021"

[dependencies]
stdweb = "0.4.20"
yew = { path = "../../..", features = ["services", "std_web"] }
